name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main

permissions:  # Add this permissions block
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    needs: test  # This ensures the build job waits for the 'test' job in codecov.yaml

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker image to GHCR
        run: |
          docker build -t ghcr.io/${{ github.repository }}/image-classification:latest .
          docker push ghcr.io/${{ github.repository }}/image-classification:latest
